/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oHcRsqJDpoW
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { SVGProps, useState } from "react";
import Link from "next/link";
import { Toggle } from "../components/ui/toggle";
import { ThemeProvider } from "next-themes"; // Assuming you are using next-themes for theming
import { cn } from "../lib/utils"; // Utility for conditional class names

export default function Component() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  return (
    <ThemeProvider attribute="class">
      <div
        className={`flex flex-col min-h-screen ${
          isDarkMode
            ? "bg-background text-card-foreground"
            : "bg-muted text-foreground"
        }`}
      >
        <header
          className={`flex justify-between items-center px-6 py-4 ${
            isDarkMode ? "bg-lightblue" : "bg-navy"
          }`}
        >
          <Link href="#" className="text-xl font-bold text-white">
            _ PG /
          </Link>
          <nav className="flex items-center gap-6">
            <Link href="#" className="hover:underline text-white">
              Actively Building
            </Link>
            <Link href="#projects" className="hover:underline text-white">
              Projects
            </Link>
          </nav>
          <Toggle
            aria-label="Toggle dark mode"
            onClick={() => setIsDarkMode(!isDarkMode)}
            className={`rounded-full p-2 ${
              isDarkMode ? "bg-lightblue" : "bg-navy"
            }`}
          >
            <SunMoonIcon className="h-6 w-6 text-white" />
          </Toggle>
        </header>

        <main className="flex flex-grow flex-col items-center justify-center">
          <div className="text-center mt-4">
            {" "}
            {/* Adjusted margin here */}
            <h1
              className={`text-4xl font-bold mb-4 ${
                isDarkMode ? "text-lightblue" : "text-navy"
              }`}
            >
              Pranay Gupta
            </h1>
            <p
              className={`mb-8 text-lg ${
                isDarkMode ? "text-lightblue" : "text-navy"
              }`}
            >
              Software Engineer. Builder. Cook.
            </p>
            <div className="flex gap-4 justify-center mb-16">
              {" "}
              {/* Increased margin for spacing */}
              <Link href="/Pranay_Gupta_Resume.pdf" className="group">
                <div
                  className={cn(
                    "flex items-center justify-center p-4 rounded-lg transition-all",
                    "group-hover:border group-hover:border-lightblue group-hover:bg-navy",
                    "text-navy group-hover:text-white"
                  )}
                >
                  <FileIcon className="h-6 w-6 mr-2 group-hover:text-white" />
                  Resume
                </div>
              </Link>
              <Link href="https://github.com/gupranay" className="group">
                <div
                  className={cn(
                    "flex items-center justify-center p-4 rounded-lg transition-all",
                    "group-hover:border group-hover:border-lightblue group-hover:bg-navy",
                    "text-navy group-hover:text-white"
                  )}
                >
                  <GithubIcon className="h-6 w-6 mr-2 group-hover:text-white" />
                  GitHub
                </div>
              </Link>
              <Link
                href="https://www.linkedin.com/in/pranay-gupta1/"
                className="group"
              >
                <div
                  className={cn(
                    "flex items-center justify-center p-4 rounded-lg transition-all",
                    "group-hover:border group-hover:border-lightblue group-hover:bg-navy",
                    "text-navy group-hover:text-white"
                  )}
                >
                  <LinkedinIcon className="h-6 w-6 mr-2 group-hover:text-white" />
                  LinkedIn
                </div>
              </Link>
            </div>
            <div className="space-y-6 text-left w-full max-w-2xl mx-auto mt-4">
              <div className="flex items-center space-x-4">
                <div className="h-16 w-16 rounded-full overflow-hidden relative">
                  <img
                    src="/spark_logo.png"
                    alt="Spark Logo"
                    className="absolute inset-0 w-full h-full object-cover"
                  />
                </div>
                <div>
                  <p className="font-semibold text-navy text-lg">
                    Ann Arbor Spark – Entrepreneurship Services Team
                  </p>
                  <p className="text-sm text-navy">
                    Full Stack Software Engineering Intern
                  </p>
                </div>
              </div>

              <div className="flex items-center space-x-4">
                <div className="h-16 w-16 rounded-full overflow-hidden relative">
                  <img
                    src="/v1_michigan_logo.jpeg"
                    alt="V1 Michigan Logo"
                    className="absolute inset-0 w-full h-full object-cover"
                  />
                </div>
                <div>
                  <p className="font-semibold text-navy text-lg">
                    V1 Michigan
                  </p>
                  <p className="text-sm text-navy">
                  Head of Product Studio & Recruitment
                  </p>
                </div>
              </div>

              <div className="flex items-center space-x-4">
                <div className="h-16 w-16 rounded-full overflow-hidden relative">
                  <img
                    src="/aipisolutions_logo.jpeg"
                    alt="AiPi Solutions Logo"
                    className="absolute inset-0 w-full h-full object-cover"
                  />
                </div>
                <div>
                  <p className="font-semibold text-navy text-lg">
                    AiPi Solutions – Legal Infrastructure Team
                  </p>
                  <p className="text-sm text-navy">
                    Software Engineering + ML Intern
                  </p>
                </div>
              </div>
            </div>
          </div>
        </main>

        <footer className="text-center p-4">
          <p className="text-sm text-navy">made by Pranay Gupta</p>
        </footer>
      </div>
     
      <img
                    src="/aipisolutions_logo.jpeg"
                    alt="AiPi Solutions Logo"
                    className="rounded-full max-w-full h-auto"

                  />
      
      
    </ThemeProvider>
  );
}

function FileIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  );
}

function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function LinkedinIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function SunMoonIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
    >
      <path d="M12 8a2.83 2.83 0 0 0 4 4 4 4 0 1 1-4-4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.9 4.9 1.4 1.4" />
      <path d="m17.7 17.7 1.4 1.4" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.3 17.7-1.4 1.4" />
      <path d="m19.1 4.9-1.4 1.4" />
    </svg>
  );
}